version: "3.0"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  
  conductor:
    build:
      context: ./conductor
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment: 
      - REDIS_URL=redis://cache
    volumes:
      - /app/node_modules
      - ./conductor:/app

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    environment: 
      - REDIS_URL=redis://cache
    volumes: 
      - ./worker:/app
